// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IContactFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** LinkedIn */
  linkedIn: string;

  /** Github */
  github: string;

  /** Email */
  email: string;

  /** Description */
  description?: string | undefined;

  /** Sub Description */
  subDescription?: string | undefined;

  /** CTA Text */
  ctaText?: string | undefined;

  /** Email Text */
  emailText?: string | undefined;

  /** Name Text */
  nameText?: string | undefined;

  /** Message */
  message?: string | undefined;

  /** Success Message */
  successMessage?: string | undefined;

  /** Submit Text */
  submitText?: string | undefined;

  /** Message Text */
  messageText?: string | undefined;
}

/** Portfolio contact content */

export interface IContact extends Entry<IContactFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contact";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEducationElementFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Degree */
  degree: string;

  /** End Date */
  endDate: string;

  /** School */
  school: string;
}

export interface IEducationElement extends Entry<IEducationElementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "educationElement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEducationsFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Educations */
  educations: IEducationElement[];
}

/** List of educated degrees acquired */

export interface IEducations extends Entry<IEducationsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "educations";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IExperienceDescriptionItemFields {
  /** Value */
  value: string;

  /** Text */
  text?: string | undefined;
}

/** Each described experience is represented here */

export interface IExperienceDescriptionItem
  extends Entry<IExperienceDescriptionItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "experienceDescriptionItem";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IExperienceElementFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Title */
  title: string;

  /** Company */
  company: string;

  /** Location */
  location: string;

  /** Description */
  description?: IExperienceDescriptionItem[] | undefined;

  /** End Date */
  endDate?: string | undefined;

  /** Start Date */
  startDate: string;

  /** Tags */
  tags?: ITagElement[] | undefined;

  /** Extra Tags */
  extraTags?: ITagElement[] | undefined;

  /** Summary */
  summary?: string | undefined;
}

export interface IExperienceElement extends Entry<IExperienceElementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "experienceElement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IExperiencesFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Experiences */
  experiences?: IExperienceElement[] | undefined;
}

/** Portfolio experiences content */

export interface IExperiences extends Entry<IExperiencesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "experiences";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomePageFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** slug */
  slug: string;

  /** CV Title */
  cvTitle?: string | undefined;

  /** About */
  about?: IPortfolioAbout | undefined;

  /** Projects */
  projects?: IPortfolioProjects | undefined;

  /** Contact */
  contact?: IContact | undefined;
}

/** Portfolio home page */

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioAboutFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** ID */
  id: string;

  /** Title */
  title: string;

  /** Description */
  description?: string | undefined;

  /** Name */
  name: string;

  /** Tags */
  tags?: ITagElement[] | undefined;

  /** Phone */
  phone?: string | undefined;

  /** Location */
  location?: string | undefined;

  /** Email */
  email?: string | undefined;

  /** LinkedIn */
  linkedIn?: string | undefined;

  /** Github */
  github?: string | undefined;

  /** Email Text */
  emailText?: string | undefined;
}

/** Portfolio about content */

export interface IPortfolioAbout extends Entry<IPortfolioAboutFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioAbout";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioCvFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Slug */
  slug?: string | undefined;

  /** Home Title */
  homeTitle?: string | undefined;

  /** About */
  about?: IPortfolioAbout | undefined;

  /** Experiences */
  experiences?: IExperiences | undefined;

  /** Educations */
  educations?: IEducations | undefined;

  /** Projects */
  projects?: IPortfolioProjects | undefined;
}

/** Portfolio resume page */

export interface IPortfolioCv extends Entry<IPortfolioCvFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioCv";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioHomeFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** slug */
  slug: string;

  /** CV Title */
  cvTitle?: string | undefined;

  /** About */
  about?: IPortfolioAbout | undefined;

  /** Projects */
  projects?: IPortfolioProjects | undefined;

  /** Contact */
  contact?: IContact | undefined;
}

/** Portfolio home page */

export interface IPortfolioHome extends Entry<IPortfolioHomeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioHome";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioProjectsFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Projects */
  projects?: IProjectElement[] | undefined;
}

/** Portfolio projects content */

export interface IPortfolioProjects extends Entry<IPortfolioProjectsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioProjects";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectElementFields {
  /** Management Title */
  managementTitle?: string | undefined;

  /** Title */
  title: string;

  /** Description */
  description?: string | undefined;

  /** Company */
  company: string;

  /** Date */
  date?: string | undefined;

  /** Info */
  info?: Document | undefined;

  /** Tags */
  tags?: ITagElement[] | undefined;

  /** Images */
  images: Asset[];

  /** Web URL */
  webUrl?: string | undefined;

  /** Github URL */
  githubUrl?: string | undefined;
}

export interface IProjectElement extends Entry<IProjectElementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "projectElement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagElementFields {
  /** Key */
  key: string;

  /** Value */
  value: string;
}

/** Simple key value pairs for tags or other needed key value pairs */

export interface ITagElement extends Entry<ITagElementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tagElement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "contact"
  | "educationElement"
  | "educations"
  | "experienceDescriptionItem"
  | "experienceElement"
  | "experiences"
  | "homePage"
  | "portfolioAbout"
  | "portfolioCv"
  | "portfolioHome"
  | "portfolioProjects"
  | "projectElement"
  | "tagElement";

export type IEntry =
  | IContact
  | IEducationElement
  | IEducations
  | IExperienceDescriptionItem
  | IExperienceElement
  | IExperiences
  | IHomePage
  | IPortfolioAbout
  | IPortfolioCv
  | IPortfolioHome
  | IPortfolioProjects
  | IProjectElement
  | ITagElement;

export type LOCALE_CODE = "en-US" | "es-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
