export const about: About = {
	id: 1,
	linkedin: "https://www.linkedin.com/in/james-gilbert-ace/",
	github: "https://github.com/gilbertoaceville",
	email: "gilbertoaceville@gmail.com",
	title: "Frontend Engineer",
	description:
		"Technically-minded and dynamic professional with rich experience in leveraging cutting-edge technologies to enhance user experiences and drive project success. Specialized in implementing strategic optimizations to improve page load times, reduce downtime, and increase overall website performance. Adept at collaborating with cross-functional teams to develop and deploy innovative features that align with business objectives. Demonstrated commitment to efficient workflow management, problem- solving, and keen eye for detail. Strong advocate for mobile-first approaches, contributing to significant boosts in customer engagement and project accomplishments. Proficient in Headless CMS, JAMstack, and Agile Methodologies. Possess suburb communication, planning, prioritization, and organization skills.",
	name: "Gilbert James",
	tags: ["Typescript", "Css"],
	phone: "+23408140942783",
	location: "Nigeria",
};

export const projects = [
	{
		id: 0,
		title: "Dodonut",
		company: "Dodonut",
		description: "Static, sustainable and highly accessible website",
		date: "04/2022",
		info: "The website build is focused on sustainability reducing website carbon emission by >80% on each page visit. Dodonut was built with Astro; it is fast, light-weight, highly performant and incorporates all accessibility techniques; svelte was employed for a few complex functionality",
		tags: ["Astro", "Svelte", "TailwindCSS", "NodeJS"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/dodonut/Screen%20Shot%202024-02-11%20at%2022.04.37_3sD2DbZ4N.webp?updatedAt=1707693985460",
			"https://ik.imagekit.io/xitvuuh9spa/dodonut/Screen%20Shot%202024-02-11%20at%2022.08.20_K6m2zFClw.webp?updatedAt=1707693987309",
			"https://ik.imagekit.io/xitvuuh9spa/dodonut/Screen%20Shot%202024-02-11%20at%2022.08.44_ATKx2wZ2t.webp?updatedAt=1707693984709",
			"https://ik.imagekit.io/xitvuuh9spa/dodonut/Screen%20Shot%202024-02-11%20at%2022.07.38_DyJvZHUbW.webp?updatedAt=1707693986645",
			"https://ik.imagekit.io/xitvuuh9spa/dodonut/Screen%20Shot%202024-02-11%20at%2022.06.56_HC1aFEvq7.webp?updatedAt=1707693984979",
		],
		href: "https://dodonut.com/",
	},
	{
		id: 1,
		title: "Portfolio v1",
		company: "personal",
		date: "12/2023",
		description:
			"Introducing the first version of my personal website built with Next14!",
		info: "Introducing my personal website! Expect updates on my experiences, upcoming projects, and tags articles.",
		tags: ["Typescript", "NextJS", "TailwindCSS"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/portfolio/screenshot1_vvIWeqz35.png",
			"https://ik.imagekit.io/xitvuuh9spa/portfolio/screenshot2_0rI98XvEB.png",
		],
		href: "https://github.com/gilbertoaceville/portfolio",
	},
	{
		id: 2,
		title: "Moebel24",
		company: "Bejamas",
		client: "Moebel GMBH",
		date: "08/2022",
		description: "E-commerce platform developed with Elastic Search",
		info: "An e-commerce platform focused on home appliances, moebel incorporates one of the most complex filtration playing with many filter categories.",
		tags: ["Typescript", "NextJS", "SCSS", "Elastic Search", "Vercel"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/moebel/Screen%20Shot%202024-02-11%20at%2022.11.22_cH9_rSDMc.webp?updatedAt=1707694066353",
			"https://ik.imagekit.io/xitvuuh9spa/moebel/Screen%20Shot%202024-02-11%20at%2022.12.52_aIF83Sbf2.webp?updatedAt=1707694062279",
			"https://ik.imagekit.io/xitvuuh9spa/moebel/Screen%20Shot%202024-02-11%20at%2022.13.34_iqZF8VT0o.webp?updatedAt=1707694066123",
		],
		href: "https://www.moebel24.de/",
	},
	{
		id: 3,
		title: "Deeptrekker",
		company: "Bejamas",
		date: "05/2023",
		client: "Deeptrekker",
		description: "Complex online shop for underwater ROVs",
		info: "Deeptrekker combines both worlds as a marketing and e-commerce website for ROVs, with a little tradeoff in performance, the website deals with large media resources.",
		tags: ["Typescript", "NextJS", "GraphQL", "Netlify", "Contentful"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/deeptrekker/Screen%20Shot%202024-02-11%20at%2022.14.26_F0Tb0rTwa.webp?updatedAt=1707693821551",
			"https://ik.imagekit.io/xitvuuh9spa/deeptrekker/Screen%20Shot%202024-02-11%20at%2022.15.40_JJS7PYnXr.webp?updatedAt=1707693827988",
			"https://ik.imagekit.io/xitvuuh9spa/configurator/Screen%20Shot%202024-02-11%20at%2022.15.57_XFowXkIRw.webp?updatedAt=1707693773023",
			"https://ik.imagekit.io/xitvuuh9spa/deeptrekker/Screen%20Shot%202024-02-11%20at%2022.16.36_dghmWtO34.webp?updatedAt=1707693812306",
		],
		href: "https://www.deeptrekker.com/",
	},
	{
		id: 3.5,
		title: "Configurator",
		company: "Bejamas",
		date: "06/2023",
		client: "Deeptrekker",
		description: "Multi step ROV build process",
		info: "The configurator is separate platform to build an ROV from scratch, it includes setting up components needed to build the ROV listed by the client on the home page, once the build is complete, a price estimation of such build is generated and the items alongside he build is sent to the Deeptrekker sales team. The content used in building this multi-step setup comes from Contentful CMS. The clients' products were originally setup in shopify; in Contentful, each product and its propertieswas gotten from shopify through the shopify app setup created in Contentful",
		tags: ["Typescript", "NextJS", "Vercel", "Shopify", "Contentful"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/configurator/Screen%20Shot%202024-02-11%20at%2022.17.42_76zGxkBo8.webp?updatedAt=1707693779764",
			"https://ik.imagekit.io/xitvuuh9spa/configurator/Screen%20Shot%202024-02-11%20at%2022.19.43_ZszHay3Jax.webp?updatedAt=1707693761923",
			"https://ik.imagekit.io/xitvuuh9spa/configurator/Screen%20Shot%202024-02-11%20at%2022.18.47_Og0GOIkIjq.webp?updatedAt=1707693756667",
			"https://ik.imagekit.io/xitvuuh9spa/configurator/Screen%20Shot%202024-02-11%20at%2022.20.07_kRJg1pmTx.webp?updatedAt=1707693779787",
		],
		href: "https://www.build.deeptrekker.com/",
	},
	{
		id: 5,
		title: "Deliverect",
		company: "Bejamas",
		date: "04/2023",
		description: "Create online stores with Deliverect",
		info: "A complex web application for managing online ordering operations, featuring a complex calculator to calculate estimations and online orders by vendors, api integration and documentation for developers use. Deliverect was developed with Gatsby, Contentful as CMS, Netlify serverless functions, data was accessed using GraphQL",
		tags: ["Javascript", "Gatsby", "GraphQL", "Netlify", "Contentful"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/deliverect/Screen%20Shot%202024-02-11%20at%2022.30.06_j4TVwfh_at.webp?updatedAt=1707693893562",
			"https://ik.imagekit.io/xitvuuh9spa/deliverect/Screen%20Shot%202024-02-11%20at%2022.30.11_PDg6-r7sV.webp?updatedAt=1707693922765",
			"https://ik.imagekit.io/xitvuuh9spa/deliverect/Screen%20Shot%202024-02-11%20at%2022.30.42_2gWAYNn2F.webp?updatedAt=1707693893546",
			"https://ik.imagekit.io/xitvuuh9spa/deliverect/Screen%20Shot%202024-02-11%20at%2022.31.19_wkpZPazOC.webp?updatedAt=1707693873416",
			"https://ik.imagekit.io/xitvuuh9spa/deliverect/Screen%20Shot%202024-02-11%20at%2022.31.19_2tBFKrpX7.webp?updatedAt=1707693929727",
		],
		href: "https://www.deliverect.com/en",
	},
	{
		id: 6,
		title: "Geo Coffee Store",
		company: "personal",
		date: "12/2021",
		description: "Locate coffee shops around you",
		info: "A simple personal coffee shop project with live geolocation services for users to locate coffee shops around them. Project was built with Next.js and Google geolocation api services",
		tags: ["Javascript", "NextJS", "Vercel", "NodeJS"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/coffe-store/Screen%20Shot%202024-02-11%20at%2022.33.49_A5W3BLu2H.webp?updatedAt=1707693720759",
			"https://ik.imagekit.io/xitvuuh9spa/coffe-store/Screen%20Shot%202024-02-11%20at%2022.34.40_Q5deP7zyi.webp?updatedAt=1707693719335",
		],
		href: "https://github.com/gilbertoaceville/geolocation-coffee-store-with-next",
	},
	{
		id: 7,
		title: "Live Search App",
		company: "personal",
		date: "09/2021",
		description: "Search for anything...",
		info: "A simple live search application integrated with upsplash api, built with React.js.",
		tags: ["React", "Netlify"],
		images: [
			"https://ik.imagekit.io/xitvuuh9spa/live-search/Screen%20Shot%202024-02-11%20at%2022.35.37_bkwRy0_2p.webp?updatedAt=1707694021251",
		],
		href: "https://github.com/gilbertoaceville/bluecube-live-search-app",
	},
];

export const experiences: Experience[] = [
	{
		id: 0,
		company: "IFMACinema",
		location: "Remote @Thuringia, Germany",
		description: [
			"- Enhanced investor confidence and secured over $100K in funding for the IFMA streaming web app by deploying cutting-edge technology, establishing performance metrics, and ensuring seamless functionality.",
			"- Implemented strategic optimization techniques on existing code base, resulting in 20% improvement in page load times.",
			"- Led the development of features for the second version of the streaming web app by collaborating with product team.",
			"- Reduced CI/CD deploy times on AWS infrastructure by 75% by accelerating feature delivery and improvements",
			"- Streamlined the development workflow through strategic code reviews, contributing to increased efficiency.",
		],
		endDate: "Present",
		startDate: "10/2020",
		title: "Frontend Engineer",
		tags: ["Nodejs", "MongoDB", "AWS", "Next.js"],
		extraTags: ["Frontend"],
		summary:
			"Improve user experience and interface responsiveness by developing and implementing innovative frontend solutions. Collaborate closely with design team to translate wireframes and mockups into functional, pixel-perfect web applications. Optimize website performance by identifying and resolving issues related to page load speed, rendering, and responsiveness. Integrate frontend components and APIs for data flow and functionality. Conduct testing and debugging of frontend applications to identify and resolve software defects.",
	},
	{
		id: 1,
		company: "Bejamas",
		location: "Remote @Wroclaw, Poland",
		description: [
			"- Researched and spearheaded development of climate-sustainable web projects, including Dodonut project, achieving reduction of >80% in website carbon emissions per page visit.",
			"- Developed and maintained services through Headless CMS, adhering to Agile, SCRUM, and Kanban methodologies, leading to 80% increase in customer retention.",
			"- Played a pivotal role in the planning and execution of high-performance website applications within the team, directly contributing to the company's impressive revenue growth from $1M to $4M in the first half of 2023.",
			"- Optimized web performance on finalized projects by over 55%, utilizing tools such as WebPageTest and Statsy for precise analysis and actionable insights; significantly reducing user bounce rate and enhancing user engagement.",
		],
		endDate: "02/2022",
		startDate: "12/2024",
		title: "Frontend Developer",
		tags: [],
		extraTags: [],
		summary: "",
	},
	{
		id: 2,
		company: "LearnFactory",
		location: "Abia, Nigeria",
		description: [
			"- Amplified customer requests for mobile/web applications by 20% with the aim of achieving consumer goals.",
			"- Elevated mobile traffic by 11% via the implementation of standardized, responsive, & mobile-first approach across all outputs.",
		],
		endDate: "10/2021",
		startDate: "03/2021",
		title: "Frontend Engineer",
		tags: [],
		extraTags: [],
		summary: "",
	},
	{
		id: 3,
		company: "Vicmie Corp",
		location: "Abia, Nigeria",
		description: [
			"- Primarily leveraged the MERN stack and worked closely with technical staff to develop complete enterprise website applications.",
			"- Implemented timely error analysis, resulting in 15% reduction in downtime and uninterrupted flow of critical processes.",
			"- Commended by management for accomplishing daily tasks on time, ensuring smooth business operations.",
		],
		endDate: "10/2020",
		startDate: "01/2020",
		title: "Web Developer",
		tags: [],
		extraTags: [],
		summary: "",
	},
];

export const educations: Education[] = [
	{
		id: 1,
		degree: "B.Sc. (Hons) in Computer Science",
		endDate: "08/2017",
		school: "Abia State University, Uturu",
	},
];
